"""drop pdf_path and sent_at from invoices

Revision ID: 395c22a6374b
Revises: f78e367e62a0
Create Date: 2026-08-28 08:14:48.997506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '395c22a6374b'
down_revision: Union[str, Sequence[str], None] = 'f78e367e62a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'pdf_path')
    op.drop_column('invoices', 'sent_at')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('invoices', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('pdf_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
